### ISSUE TITLE
question: API key generation fails (password length exceeds 72 bytes) : how to fix that ?

### ISSUE THREAD

**Issue by pav67** [greenpau/caddy-security#224]
Hello,

I can't generate an API key through the auth portal, whenever I try I'm getting the following error :
FAIL: password generation error: bcrypt: password length exceeds 72 bytes
<img width="1033" alt="Screenshot API key fail" src="https://user-images.githubusercontent.com/313517/230592909-802b7c5d-7a4c-4b9c-b804-054d9bd5fe5a.png">

Is there something to configure somewhere that I'm missing ?
Thanks for your help!

**Comment by greenpau** [comment]
@pav67 , that is a bug. There were recent changes to bcrypt library. Will fix and make a new release. Thank you for reporting this!

**Comment by EntropyValley** [comment]
Any updates on this @greenpau? API Key Generation still seems to be broken in the current version.

**Comment by greenpau** [comment]
@EntropyValley , I need to find some time to update this module.

**Comment by sdsys-ch** [comment]
@greenpau , I've created a dirty fix for this issue in a private repo. I'm not sure if it breaks anything or if there are security considerations I'm not aware of?

I've tested this locally and my fix allows authentication via X-Api-Key Header with ApiKeys generated via the local portal (diff for [go-authcrunch - pkg:identity:database.go](https://github.com/greenpau/go-authcrunch/blob/main/pkg/identity/database.go)):

```diff
@@ -566,7 +566,7 @@ func (db *Database) AddAPIKey(r *requests.Request) error {
        if err != nil {
                return errors.ErrAddAPIKey.WithArgs(r.Key.Usage, err)
        }
-       s := GetRandomStringFromRange(72, 96)
+       s := GetRandomString(72)
        failCount := 0
        for {
                hk, err := NewPassword(s)
```

Since bcrypt now enforces a hard limit of 72 (non-unicode) chars, this fixes the issue.

If you don't see any issues with this, I can create a pull request. If not, let me know what I've overlooked and I might try to fix my patch?

**Comment by greenpau** [comment]
@sdsys-ch , I would try looking at it this week.

**Comment by greenpau** [comment]
@sdsys-ch , @pav67 , @EntropyValley , I added a fix for this. Will be available in the next release.

**Comment by sdsys-ch** [comment]
Appreciated! Great to see all the activity around caddy-security. Thanks

**Comment by greenpau** [comment]
@sdsys-ch , thank you for the gift! Much appreciated 🎉

**Comment by greenpau** [comment]
@pav67, @sdsys-ch , @EntropyValley , I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?
