### ISSUE TITLE
🔥 announcement 🔥: introducing identity stores and providers

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-security#83]
Will be abandoning the `backends` concept and  and introducing:

1. **IdentityStore** (Local & LDAP), and
2. **IdentityProvider** (OAuth/OpenID & SAML).

**Note**: The `method` keyword is going away. The `provider` keyword was renamed to `driver`.

## Identity Stores

Previously, your local config was a part of **authentication portal**.

```
	security {
		authentication portal myportal {
			backend local {env.HOME}/.local/caddy/users.json local
```

Now, it is in its own category and getting attached to a portal via `enable identity store <name>`.

```
security {

  local identity store localdb {
    realm local
    path assets/config/users.json
  }

  authentication portal myportal {
    enable identity store localdb
  }

}
```

## Identity Providers

Previously, your OAuth config was a part of **authentication portal**.

```
	security {
		authentication portal myportal {
			backends {
				google_oauth2_backend {
					method oauth2
					realm google
					provider google
					client_id {env.GOOGLE_CLIENT_ID}.apps.googleusercontent.com
					client_secret {env.GOOGLE_CLIENT_SECRET}
					scopes openid email profile
				}
			}
```

Now, it is in its own category and getting attached to a portal via `enable identity provider <name>`.

```
security {

  oauth identity provider google {
    realm google
    driver google
    client_id {env.GOOGLE_CLIENT_ID}.apps.googleusercontent.com
    client_secret {env.GOOGLE_CLIENT_SECRET}
    scopes openid email profile
  }

  # alternatively use shortcut
  # oauth identity provider google {env.GOOGLE_CLIENT_ID} {env.GOOGLE_CLIENT_SECRET}

  authentication portal myportal {
    enable identity provider google
  }

}
```

**Comment by ouuan** [comment]
Why is this a patch version bump? Does Caddy Security follow semver?

**Comment by tpansino** [comment]
@greenpau, first of all thank you for the great project. 🙏 It's because this project is so excellent that I'd like to offer some polite feedback on how this breaking change was released.

First, you mentioned that this probably warranted a minor version bump. I don't see anything in the README that says explicitly that you're following [Semantic Versioning](https://semver.org/), but if you are (and I think you should), then this change was definitely a major version bump. Anytime you're going to break a user contract (changing a config structure, API, feature removal, etc) with a plugin like this, it's worth it to communicate that to users via a major bump. That way users know they can't just expect to download the new version of the software, reload Caddy, and everything will just work(TM). This also plays well with package/plugin managers, which typically recommend users set their version constraints to accept patches and minors, but not majors, so that they don't blindly break their applications when upgrading.

Second, you also need documentation on how/what to migrate with each major change. As it stands, I downloaded the new verison and my Caddy broke without any useful log information, just raw stack traces. It took me some time to figure out (A) Caddy Security had breaking changes, not Caddy (B) what exactly changed in the config structure. Though reasonable, your examples above still required me to diff against my (rather complex) config and ultimately dive in to the source code to figure out that `method` was dropped and `provider` renamed to `driver`. All of that is friction to continuing to use your great work, and can serve to drive users off. I recommend releasing documentation updates in tandem with changes, especially for breaking, and specifically highlighting breaking change documentation either in the notes of the GitHub release, or in a separate `CHANGELOG.md`. Make it easy for users to see your intended migration path.

Thanks for your time, and I look forward to your continued success.

**Comment by greenpau** [comment]
@tpansino , thank you for the feedback. i will update the notes related to provider/driver. I am glad it worked out for you. 

Next time, prior to diving deep into the source code, please open an issue. I will be able to analyze it faster and offer advice. Additionally, I would be able to amend/add docs to offer better documentation. (E.g. I still need to update configs in authp website). If I don’t hear from people, I might now do it right away (because it may be on a backlog for me after a change of 6K lines of code).

As to semver, I don’t want to update major versions, because I don’t want to deal with go versioning challenges, i.e. having /vX in a path.
