### ISSUE TITLE
How to perform LDAP authentication/authorization via command line

### ISSUE THREAD

**Issue by hahattan** [greenpau/caddy-security#94]
**Describe the issue**

I'm trying to create a proof of concept of using LDAP for authentication. 
Most of the thing went well and I just got 2 questions:

1. How do I see "My Identity" after successfully login ? If I visit `localhost:2016` and login with LDAP username/password it'll lead me to a blank page. (I guess I miss something in my configuration)
I also tried to invoke the `/whoami` endpoint with access_token I got in the browser but there's no response.

2.  How to perform the authentication/authorization via command line ?
For example I expect something like `curl <some-options ... > localhost:2016/data/api/ping`

**Configuration**

```
{
	debug

	order authenticate before respond
	#order authorize before basicauth

	security {
		ldap identity store demo.com {
			realm demo.com
			servers {
				ldap://ldap.forumsys.com posix_groups
			}
			attributes {
				name cn
				surname foo
				username uid
				member_of uniqueMember
				email mail
			}
			username "cn=read-only-admin,dc=example,dc=com"
			password "password"
			search_base_dn "DC=EXAMPLE,DC=COM"
			search_filter "(&(|(uid=%s)(mail=%s))(objectClass=inetOrgPerson))"
			groups {
				"ou=mathematicians,dc=example,dc=com" developer
				"ou=scientists,dc=example,dc=com" user
			}
		}

		authentication portal myportal {
			crypto default token lifetime 3600
			enable identity store demo.com
                         cookie insecure on
                         ui {
				logo url "https://caddyserver.com/resources/images/caddy-circle-lock.svg"
				logo description "Caddy"
				links {
					"My Identity" "/whoami" icon "las la-user"
				}
				password_recovery_enabled yes
			}
		}

		authorization policy mypolicy {
			# disable auth redirect
			set auth url /auth
			allow roles developer
		}
	}
}

:2016 {
    route /auth* {
        authenticate with myportal
    }

    route /data/* {
        authorize with mypolicy
        uri strip_prefix /data
        reverse_proxy data:59880
    }

    route {
        authorize with mypolicy
    }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

```
...

dns.providers.cloudflare v0.0.0-20210607183747-91cf700356a1
http.authentication.providers.authorizer v1.1.5
http.handlers.authenticator v1.1.5
http.handlers.trace v1.1.8
security v1.1.5

  Non-standard modules: 5
```

**Expected behavior**

Describe expected behavior.

**Additional context**

**Comment by greenpau** [comment]
> How do I see "My Identity" after successfully login ? If I visit localhost:2016 and login with LDAP username/password it'll lead me to a blank page. (I guess I miss something in my configuration)

Please see various configuration files based on this query: https://github.com/authp/authp.github.io/search?q=My+Identity

Specifically: https://github.com/authp/authp.github.io/blob/main/assets/conf/ldap/Caddyfile

The auth portal works on your `https` interface. What do you see when you browse to `https://localhost:2016/auth/`?

If your interface is HTTP, then you need to use `cookie insecure on` https://authp.github.io/docs/authenticate/auth-cookie#intra-domain-cookies


> I also tried to invoke the /whoami endpoint with access_token I got in the browser but there's no response.

Since you are serving the portal on `/auth`, then, you need to browse to `/auth/whoami`.

> How to perform the authentication/authorization via command line ? For example I expect something like curl <some-options ... > localhost:2016/data/api/ping

Please see here for `curl`: https://authp.github.io/docs/authenticate/misc#json-api

Additionally, I am working on this tool to be able getting a token. https://github.com/greenpau/go-authcrunch/tree/main/cmd/authdbctl#getting-started

@hahattan , please ask follow up questions! 👍

**Comment by hahattan** [comment]
> Since you are serving the portal on `/auth`, then, you need to browse to `/auth/whoami`.

This solved both of my question, thanks for the help .
